/**
 * PDF Report Generator
 * 
 * PDFKit kullanarak bilişsel tarama sonuç raporu oluşturur.
 * Multi-language (TR/EN) desteği vardır.
 */

const PDFDocument = require('pdfkit');
const path = require('path');
const { createLogger } = require('../lib/logger');
const { normalizeLanguage, isEnglish } = require('../lib/language');

const FONTS_DIR = path.join(__dirname, '..', 'assets', 'fonts');
const FONT_REGULAR = path.join(FONTS_DIR, 'NotoSans-Regular.ttf');
const FONT_BOLD = path.join(FONTS_DIR, 'NotoSans-Bold.ttf');

const log = createLogger('PDFGenerator');

const TEXT = {
  tr: {
    title: 'Bilişsel Tarama Sonuç Raporu',
    subtitle: 'Nöra - Yapay Zeka Destekli Bilişsel Tarama',
    date: 'Tarih',
    patient: 'Katılımcı',
    totalScore: 'Toplam Puan',
    riskLevel: 'Risk Seviyesi',
    riskLevels: { LOW: 'Düşük Risk', MODERATE: 'Orta Risk', HIGH: 'Yüksek Risk' },
    testDetails: 'Test Detayları',
    testNames: {
      VERBAL_FLUENCY: 'Sözel Akıcılık',
      STORY_RECALL: 'Hikaye Hatırlama',
      VISUAL_RECOGNITION: 'Görsel Tanıma',
      ORIENTATION: 'Yönelim',
      VIDEO_ANALYSIS: 'Video Analizi',
    },
    score: 'Puan',
    maxScore: 'Maks. Puan',
    successRate: 'Başarı Oranı',
    disclaimer: 'UYARI: Bu rapor tıbbi bir teşhis niteliği taşımamaktadır. Sonuçlar yalnızca ön tarama amaçlıdır. Kesin değerlendirme için bir sağlık kuruluşuna başvurunuz.',
    generatedBy: 'Bu rapor Nöra yapay zeka sistemi tarafından otomatik olarak oluşturulmuştur.',
    noTests: 'Test sonucu bulunamadı.',
  },
  en: {
    title: 'Cognitive Screening Report',
    subtitle: 'Nöra - AI-Powered Cognitive Screening',
    date: 'Date',
    patient: 'Participant',
    totalScore: 'Total Score',
    riskLevel: 'Risk Level',
    riskLevels: { LOW: 'Low Risk', MODERATE: 'Moderate Risk', HIGH: 'High Risk' },
    testDetails: 'Test Details',
    testNames: {
      VERBAL_FLUENCY: 'Verbal Fluency',
      STORY_RECALL: 'Story Recall',
      VISUAL_RECOGNITION: 'Visual Recognition',
      ORIENTATION: 'Orientation',
      VIDEO_ANALYSIS: 'Video Analysis',
    },
    score: 'Score',
    maxScore: 'Max Score',
    successRate: 'Success Rate',
    disclaimer: 'DISCLAIMER: This report does not constitute a medical diagnosis. Results are for preliminary screening purposes only. Please consult a healthcare provider for a definitive evaluation.',
    generatedBy: 'This report was automatically generated by the Nöra AI system.',
    noTests: 'No test results found.',
  },
};

function getTexts(language) {
  return isEnglish(normalizeLanguage(language)) ? TEXT.en : TEXT.tr;
}

function formatDateForPdf(dateStr, language) {
  const date = new Date(dateStr);
  const locale = isEnglish(language) ? 'en-US' : 'tr-TR';
  return date.toLocaleDateString(locale, {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

/**
 * PDF raporu oluşturur ve Buffer olarak döner
 * @param {Object} session - TestSession (tests dahil)
 * @param {Object} user - User objesi
 * @param {string} language - 'tr' | 'en'
 * @returns {Promise<Buffer>}
 */
async function generatePdfReport(session, user, language = 'en') {
  const lang = normalizeLanguage(language);
  const t = getTexts(lang);

  log.info('PDF raporu oluşturuluyor', { sessionId: session.id, language: lang });

  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ 
        size: 'A4', 
        margin: 50,
        info: {
          Title: t.title,
          Author: 'Nöra AI',
          Subject: t.subtitle,
        },
      });

      const chunks = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => {
        const pdfBuffer = Buffer.concat(chunks);
        log.info('PDF raporu oluşturuldu', { sessionId: session.id, size: pdfBuffer.length });
        resolve(pdfBuffer);
      });
      doc.on('error', (err) => {
        log.error('PDF oluşturma hatası', { error: err.message });
        reject(err);
      });

      // ── Font kayıt ──
      doc.registerFont('NotoSans', FONT_REGULAR);
      doc.registerFont('NotoSans-Bold', FONT_BOLD);

      // ── Header ──
      doc.fontSize(24).font('NotoSans-Bold').fillColor('#111827')
        .text(t.title, { align: 'center' });
      doc.fontSize(11).font('NotoSans').fillColor('#6B7280')
        .text(t.subtitle, { align: 'center' });
      doc.moveDown(0.5);

      // Divider
      doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#E5E7EB').lineWidth(1).stroke();
      doc.moveDown(1);

      // ── Katılımcı Bilgileri ──
      const infoY = doc.y;
      doc.fontSize(10).font('NotoSans').fillColor('#9CA3AF')
        .text(`${t.patient}:`, 50, infoY);
      doc.fontSize(12).font('NotoSans-Bold').fillColor('#111827')
        .text(user.name, 50, infoY + 14);

      doc.fontSize(10).font('NotoSans').fillColor('#9CA3AF')
        .text(`${t.date}:`, 300, infoY);
      doc.fontSize(12).font('NotoSans-Bold').fillColor('#111827')
        .text(formatDateForPdf(session.startedAt, lang), 300, infoY + 14);

      doc.moveDown(2.5);

      // ── Toplam Skor Kutusu ──
      const boxY = doc.y;
      doc.roundedRect(50, boxY, 495, 80, 8).fillAndStroke('#F9FAFB', '#E5E7EB');

      // Toplam puan
      doc.fontSize(10).font('NotoSans').fillColor('#9CA3AF')
        .text(t.totalScore, 70, boxY + 15);
      const scoreText = session.totalScore !== null ? Math.round(session.totalScore).toString() : '—';
      doc.fontSize(32).font('NotoSans-Bold').fillColor('#111827')
        .text(scoreText, 70, boxY + 32);

      // Risk seviyesi
      if (session.riskLevel) {
        const riskLabel = t.riskLevels[session.riskLevel] || session.riskLevel;
        const riskColors = { LOW: '#059669', MODERATE: '#D97706', HIGH: '#DC2626' };
        const riskColor = riskColors[session.riskLevel] || '#6B7280';

        doc.fontSize(10).font('NotoSans').fillColor('#9CA3AF')
          .text(t.riskLevel, 350, boxY + 15);
        doc.fontSize(18).font('NotoSans-Bold').fillColor(riskColor)
          .text(riskLabel, 350, boxY + 35);
      }

      doc.y = boxY + 100;

      // ── Test Detayları ──
      doc.fontSize(14).font('NotoSans-Bold').fillColor('#111827')
        .text(t.testDetails, 50, doc.y);
      doc.moveDown(0.8);

      const tests = session.tests || [];
      if (tests.length === 0) {
        doc.fontSize(11).font('NotoSans').fillColor('#9CA3AF')
          .text(t.noTests);
      } else {
        // Tablo başlıkları
        const tableX = 50;
        const colWidths = [180, 80, 80, 100];
        const headerY = doc.y;

        doc.fontSize(9).font('NotoSans-Bold').fillColor('#6B7280');
        doc.text('Test', tableX, headerY);
        doc.text(t.score, tableX + colWidths[0], headerY);
        doc.text(t.maxScore, tableX + colWidths[0] + colWidths[1], headerY);
        doc.text(t.successRate, tableX + colWidths[0] + colWidths[1] + colWidths[2], headerY);

        doc.moveDown(0.5);
        doc.moveTo(tableX, doc.y).lineTo(545, doc.y).strokeColor('#E5E7EB').lineWidth(0.5).stroke();
        doc.moveDown(0.5);

        for (const test of tests) {
          const rowY = doc.y;
          const testName = t.testNames[test.testType] || test.testType;
          const pct = test.maxScore > 0 ? Math.round((test.score / test.maxScore) * 100) : 0;
          const pctColor = pct >= 75 ? '#059669' : pct >= 50 ? '#D97706' : '#DC2626';

          doc.fontSize(11).font('NotoSans-Bold').fillColor('#111827')
            .text(testName, tableX, rowY, { width: colWidths[0] - 10 });
          doc.fontSize(11).font('NotoSans').fillColor('#374151')
            .text(Math.round(test.score).toString(), tableX + colWidths[0], rowY);
          doc.text(test.maxScore.toString(), tableX + colWidths[0] + colWidths[1], rowY);
          doc.font('NotoSans-Bold').fillColor(pctColor)
            .text(`%${pct}`, tableX + colWidths[0] + colWidths[1] + colWidths[2], rowY);

          doc.moveDown(0.8);

          // Progress bar
          const barY = doc.y;
          const barWidth = 200;
          doc.roundedRect(tableX, barY, barWidth, 6, 3).fill('#E5E7EB');
          if (pct > 0) {
            doc.roundedRect(tableX, barY, Math.max(6, (barWidth * pct) / 100), 6, 3).fill(pctColor);
          }

          doc.y = barY + 16;
          doc.moveTo(tableX, doc.y).lineTo(545, doc.y).strokeColor('#F3F4F6').lineWidth(0.5).stroke();
          doc.moveDown(0.5);
        }
      }

      // ── Uyarı ──
      doc.moveDown(1.5);
      const disclaimerY = doc.y;
      doc.roundedRect(50, disclaimerY, 495, 60, 6).fillAndStroke('#FEF3C7', '#FDE68A');
      doc.fontSize(8).font('NotoSans-Bold').fillColor('#92400E')
        .text(t.disclaimer, 65, disclaimerY + 12, { width: 465, lineGap: 3 });

      // ── Footer ──
      doc.moveDown(2);
      doc.fontSize(8).font('NotoSans').fillColor('#9CA3AF')
        .text(t.generatedBy, { align: 'center' });
      doc.text(`Session ID: ${session.id}`, { align: 'center' });

      doc.end();
    } catch (err) {
      log.error('PDF oluşturma hatası', { error: err.message });
      reject(err);
    }
  });
}

module.exports = { generatePdfReport };
